version: '3'

volumes:
  wordpress-db:
  mariadb-db:

networks:
  infra:
    driver: bridge

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    image: nginx:tag
    networks:
      - infra
    volumes:
      - type: volume
        source: wordpress-db
        target: /var/www/html
        volume:
          nocopy: true
    ports:
      - 443:443
    restart : always

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    image: wordpress:tag
    networks:
      - infra
    volumes:
      - type: volume
        source: wordpress-db
        target: /var/www/html
        volume:
          nocopy: true
    env_file:
      - .env
    restart : always

  mariadb:
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
    image: mariadb:tag
    networks:
      - infra
    volumes:
      - type: volume
        source: mariadb-db
        target: /var/lib/mysql
        volume:
          nocopy: true
    env_file:
      - .env
    restart : always
