version: '3'

networks:
  infra:
    driver: bridge
volumes:
    mariadb-db:
      driver: local
      driver_opts:
        type: volumes
        o: bind
        device: /home/jaemjeon/data/mariadb
    wordpress-db:
      driver: local
      driver_opts:
        type: volumes
        o: bind
        device: /home/jaemjeon/data/wordpress
services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    image: nginx:jaemjeon
    networks:
      - infra
    volumes:
      - wordpress-db:/var/www/html
    ports:
      - 443:443
    env_file:
      - .env
    restart : always

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    image: wordpress:jaemjeon
    networks:
      - infra
    volumes:
      - wordpress-db:/var/www/html
    env_file:
      - .env
    restart : always

  mariadb:
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
    image: mariadb:jaemjeon
    networks:
      - infra
    volumes:
      - mariadb-db:/var/lib/mysql
    env_file:
      - .env
    restart : always
