version: '3'

volumes: {}
networks:
  infra:
    driver: bridge

services:
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirement/nginx
      dockerfile: Dockerfile
    image: nginx:tag
    networks:
      - infra
    volumes:
      - /home/jaemjeon/data/wordpress:/var/www/html
    ports:
      - 443:443
    restart : always

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirement/wordpress
      dockerfile: Dockerfile
    image: wordpress:tag
    networks:
      - infra
    volumes:
      - /home/jaemjeon/data/wordpress:/var/www/html
    env_file:
      - .env
    restart : always

  mariadb:
    build:
      context: ./requirement/mariadb
      dockerfile: Dockerfile
    image: mariadb:tag
    networks:
      - infra
    volumes:
      - /home/jaemjeon/data/mariadb:/var/lib/mysql
    env_file:
      - .env
    restart : always
